import { Helmet } from "react-helmet-async";

interface BreadcrumbItem {
  name: string;
  url: string;
}

interface SEOProps {
  title: string;
  description: string;
  canonical: string;
  /** One JSON-LD object, or several. */
  schema?: object | object[];
  breadcrumbs?: BreadcrumbItem[];
  /** Keep private or utility pages (admin, sign-in) out of search results. */
  noindex?: boolean;
  /** Open Graph type; "article" for Insights posts. */
  type?: "website" | "article";
  /** Share image; defaults to the page's own card in /og/. */
  image?: string;
}

// Every indexed page has a branded 1200x630 share card at /og/<path>.jpg
// (generated by scripts/make-og-images.py from the sitemap).
const ogImageFor = (canonical: string) => {
  try {
    const path = new URL(canonical).pathname.replace(/\/+$/, "");
    const slug = path === "" ? "home" : path.slice(1).replace(/\//g, "--");
    return `https://giftcityfunds.in/og/${slug}.jpg`;
  } catch {
    return "https://giftcityfunds.in/og/home.jpg";
  }
};

export const SEO = ({ title, description, canonical, schema, breadcrumbs, noindex, type = "website", image }: SEOProps) => {
const ogImage = image ?? (noindex ? "https://giftcityfunds.in/og/home.jpg" : ogImageFor(canonical));
const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": "https://giftcityfunds.in/#organization",
  "name": "GIFT City Funds",
  "alternateName": ["GIFTCityFunds", "giftcityfunds.in", "Gift City Funds"],
  "url": "https://giftcityfunds.in",
  "logo": "https://giftcityfunds.in/favicon-512.png",
  "knowsAbout": ["GIFT City", "IFSC", "IFSCA", "GIFT City mutual funds", "Liberalised Remittance Scheme", "NRI investing"],
  "founder": {
    "@type": "Person",
    "@id": "https://giftcityfunds.in/about#anup-vatyani",
    "name": "Anup Vatyani",
    "url": "https://giftcityfunds.in/about",
    "image": "https://giftcityfunds.in/images/anup-vatyani.jpg",
    "jobTitle": "Mutual Fund Distributor",
    "identifier": "ARN106715"
  },
  "description": "Informational platform about GIFT City and IFSC mutual fund frameworks. No investment advice.",
  "contactPoint": [{
    "@type": "ContactPoint",
    "email": "info@giftcityfunds.in",
    "contactType": "Customer Service",
    "areaServed": "IN"
  }],
  "sameAs": ["https://www.linkedin.com/in/anup-vatyani-081b4142"]
};

const websiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": "https://giftcityfunds.in/#website",
  "name": "GIFT City Funds",
  "alternateName": ["GIFTCityFunds", "giftcityfunds.in"],
  "url": "https://giftcityfunds.in",
  "description": "Educational guide to GIFT City IFSC funds for NRIs, OCIs and resident Indians: fund types, LRS and TCS, taxation and how to invest.",
  "inLanguage": "en-IN",
  "publisher": { "@id": "https://giftcityfunds.in/#organization" },
};

// Fill in the fields Google expects on every Article so individual pages
// only need to state what is specific to them.
const SITE_FIRST_PUBLISHED = "2026-07-23";
const enrich = (item: object): object => {
  const s = item as Record<string, unknown>;
  if (s["@type"] !== "Article") return item;
  return {
    ...s,
    image: s.image ?? ogImage,
    datePublished: s.datePublished ?? SITE_FIRST_PUBLISHED,
    dateModified: s.dateModified ?? s.datePublished ?? SITE_FIRST_PUBLISHED,
    author: {
      "@type": "Person",
      "@id": "https://giftcityfunds.in/about#anup-vatyani",
      name: "Anup Vatyani",
      url: "https://giftcityfunds.in/about",
      image: "https://giftcityfunds.in/images/anup-vatyani.jpg",
      identifier: "ARN106715",
    },
    publisher: { "@id": "https://giftcityfunds.in/#organization" },
  };
};
const pageSchemas = (schema ? (Array.isArray(schema) ? schema : [schema]) : []).map(enrich);

  return (
    <Helmet>
      {/* Primary Meta Tags */}
      <title>{title}</title>
      <meta name="title" content={title} />
      <meta name="description" content={description} />
      <meta name="robots" content={noindex ? "noindex, nofollow" : "index, follow"} />
      
      {/* Canonical URL */}
      <link rel="canonical" href={canonical} />
      
      {/* Open Graph / Facebook */}
      <meta property="og:site_name" content="GIFT City Funds" />
      <meta property="og:type" content={type} />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:url" content={canonical} />
      <meta property="og:image" content={ogImage} />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta property="og:image:alt" content={title} />
      <meta property="og:locale" content="en_IN" />
      
      {/* Twitter */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={ogImage} />
      
      {/* Structured Data - Organization */}
      <script type="application/ld+json">
        {JSON.stringify(organizationSchema)}
      </script>
      
      {/* Structured Data - Financial Service */}
      <script type="application/ld+json">
        {JSON.stringify(websiteSchema)}
      </script>
      
      {/* Additional Page-Specific Schema */}
      {pageSchemas.map((item, i) => (
        <script key={i} type="application/ld+json">
          {JSON.stringify(item)}
        </script>
      ))}
      
      {/* BreadcrumbList Schema */}
      {breadcrumbs && breadcrumbs.length > 0 && (
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": breadcrumbs.map((crumb, index) => ({
              "@type": "ListItem",
              "position": index + 1,
              "name": crumb.name,
              "item": crumb.url
            }))
          })}
        </script>
      )}
    </Helmet>
  );
};
